apiVersion: 1

datasources:
  - name: Norwegian Dam Database
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: dam_monitor_2024
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: true
    isDefault: true
    editable: true 